<?php
/** 
 *  Title Pop
 *  Carry the node title via a CTA to a webform autocompletion.
 */

function page_title_manage_init() {

   }


function page_title_manage_menu() {
  $items = array();
  $items['admin/page_title_manage'] = array(
              'title' => 'Page Title Management',
              'page callback' => 'page_title_manage_page',
              'access arguments' => array('access page_title_manage content'),
              'description' => 'Title POP Control Page',
              'access callback' => TRUE,
              'type' => MENU_NORMAL_ITEM,
          );
   return $items;
}

function page_title_manage_page() {
  // Are you an admin? Hope so.
  // Obviously this should be based on permissions, not hard-coded role.
    global $user;
  if ($user->uid == 1) {
    return drupal_get_form('page_title_manage_form');
  }
   else {
  // ...or else returnes a blank page
    return drupal_get_form();
  }
}

function page_title_manage_form($form, &$form_state) {




  $form['markup'] = array(
    '#markup' => $markup,
    '#title' => t(''),
    );



/**
 *   SUBMIT
 */
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

 $form['#submit'][] = 'page_title_manage_form_submit';

  return $form;

}


function page_title_manage_form_submit($form, $form_state) {

   db_insert('page_title_manage')
         ->fields(array('content_type', 'content_element', 'webform', 'webform_component'))
         ->values(array(
           'content_type'      => $form_state['input']['content_type'],
           'content_element'   => $form_state['input']['dropdown_second'],
           'webform'           => $form_state['input']['webforms'],
           'webform_component' => $form_state['input']['dropdown_second_element'],

         ))
        ->execute();
}


